### ISSUE TITLE
[Bug] `--email` flag on `bgc-company list` does not appear to filter

### ISSUE THREAD

**Issue by flossypurse** [temporalio/background-checks#15]
<img width="1019" alt="Screen Shot 2022-01-04 at 1 40 13 PM" src="https://user-images.githubusercontent.com/34380806/148121156-2ba53349-cfbe-493b-a53c-a1fb5d500508.png">

**Comment by robholland** [comment]
Good spot. Fixed in b32a3fd1d6f5d26c0149d38fb0ebf54ded9976a7. It will need you to wipe the docker compose setup and re-run `./start` so that the CandidateEmail search attribute gets created as `keyword`.
