### ISSUE TITLE
[Bug] Empty Search Attributes

### ISSUE THREAD

**Issue by MStreet3** [temporalio/background-checks#46]
### What are you really trying to do?

I would like to view the status of all current workflow executions, but the status is empty.

### Describe the bug

I started a new workflow and then listed the running workflows, but the status and email are empty.

### Minimal Reproduction

```bash
$ cd background-checks
$ ./start
$ ./run-cli bgc-company --email your@example.com
Created check
$ ./run-cli bgc-company list
Background Checks:
ID: <RUN_ID> Email:  Status: 
```

### Environment/Versions
MacOS 13.5 Ventura
Intel i9
commit: 0425e4069dffad892061058a090bc4ad8d41e371

**Comment by robholland** [comment]
I think this is fixed by #47 because this is working for me now. Please retry once that is merged and confirm.
